FROM ubuntu:20.04

ARG USERNAME=vscode
ARG USER_UID=1000
ARG USER_GID=$USER_UID

RUN groupadd --gid $USER_GID $USERNAME 
RUN useradd --uid $USER_UID --gid $USER_GID -m $USERNAME 
#
# Update & upgrade
#
# RUN export DEBIAN_FRONTEND=noninteractive 
RUN DEBIAN_FRONTEND=noninteractive apt-get update 
RUN DEBIAN_FRONTEND=noninteractive apt-get upgrade 
#
# Add sudo support
#
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y sudo 
RUN echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME
RUN chmod 0440 /etc/sudoers.d/$USERNAME 
#
# Install required packages (and zsh)
#
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y git \
    curl \
    wget \
    bash \
    zsh \
    zsh-syntax-highlighting \
    zsh-autosuggestions \
    software-properties-common \
    apt-transport-https \
    jq \
    unzip \
    gnupg \
    lsb-release 
#
# Install az cli
#
RUN set -v && curl -sL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | tee /etc/apt/trusted.gpg.d/microsoft.asc.gpg >/dev/null \
    && CLI_REPO=$(lsb_release -cs) &&  echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ ${CLI_REPO} main" | tee /etc/apt/sources.list.d/azure-cli.list 
RUN DEBIAN_FRONTEND=noninteractive apt-get update 
RUN DEBIAN_FRONTEND=noninteractive set +v && apt-get install -y azure-cli 
#
# Install terraform & tflint
#
RUN TF_VER=$(curl -s https://checkpoint-api.hashicorp.com/v1/check/terraform | jq -r -M '.current_version') \
    && curl "https://releases.hashicorp.com/terraform/${TF_VER}/terraform_${TF_VER}_linux_amd64.zip" --output ~/terraform_${TF_VER}_linux_amd64.zip \
    && unzip ~/terraform_${TF_VER}_linux_amd64.zip -d /usr/local/bin \
    && rm ~/terraform_${TF_VER}_linux_amd64.zip

RUN TFLINT_URL="https://github.com/terraform-linters/tflint/releases/latest/download/tflint_linux_amd64.zip" \
    && curl -L $TFLINT_URL --output ~/tflint_linux_amd64.zip 
RUN unzip ~/tflint_linux_amd64.zip -d /usr/local/bin 
RUN rm ~/tflint_linux_amd64.zip 

USER $USERNAME

RUN echo "alias t='noglob terraform'" | tee -a ~/.zshrc 
RUN echo "alias terraform='noglob terraform'" | tee -a ~/.zshrc
